[export]
url = 'https://api.example.com'
token = 'secret-token'

[restaurants.johanneberg]
rss = [
    'http://intern.chalmerskonferens.se/view/restaurant/karrestaurangen/Veckomeny.rss'
]

[restaurants.lindholmen]
rss = [
    'http://intern.chalmerskonferens.se/view/restaurant/l-s-kitchen/Projektor.rss'
]
